### ISSUE TITLE
Awake DestroyObject with condition?

### ISSUE THREAD

**Issue by lexnewgate** [UnityCommunity/UnitySingleton#1]
```csharp
  protected virtual void Awake()
    {
        if (instance == null)
        {
            instance = this as T;
            DontDestroyOnLoad(gameObject);
        }
        else if (instance != this)
        {
            //If there is already an instance of this class, destroy the object we just created.
            Debug.LogWarning("Attempted to spawn more then one singleton object. destroying new instance of " + gameObject.ToString() + "\nIf you would like more than one instance, ensure that the class you have written does not Inherit from a Singleton class.");
            Destroy(gameObject);
        }
    }
```
I found [another snippet](https://github.com/Naphier/unity-design-patterns/blob/7e826637ec559c0dc859f0ae059b91c6aa134e59/Assets/singleton/structure/Singleton.cs#L30) from Naphier which the `instance!=this` make sense when destroy it.

Could you please explain it why you didn't add condition? Thanks.

**Comment by hasanbayatme** [comment]
Hi.
That's the same, which condition do you mean?
As I see, both scripts work the same way.

Thanks.

**Comment by lexnewgate** [comment]
Sorry for wasting your time as a unity novice. I thought awake will be invoked when the gameobject is enabled. I didn't realize it will be only invoked once during its lifetime.

**Comment by hasanbayatme** [comment]
Ah, no problem, that's my pleasure.
